import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";

const jose = Josefin_Sans({
  weight: ["600"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jose.className}>{children}</body>
    </html>
  );
}
